name: dl-project
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  # PyTorch stack via canale ufficiale pytorch+nvidia (NON via pip)
  - pytorch=2.4.*
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  # Pacchetti scientifici via conda-forge (più stabili per Windows)
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pyyaml
  - tqdm
  - tensorboard
  - seaborn
  - pillow
  - jupyter
  - ipykernel
  # Lmdb tramite pip perché su conda-forge a volte ha problemi su Windows
  - pip:
      - lmdb